### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by AmbreM71** [andrewsyc/Tomb-Raider-1-2-3-4-Map-viewer-and-levels#2]
TombViewer doesn't work on my computer. I got violation access. I tried with compatibility settings but it still don't work. If you can find a solution, it would be very great :)
![2018-05-04 21_42_49-tomb-raider-1-2-3-4-5-map-viewer-and-levels-master](https://user-images.githubusercontent.com/31449380/39648917-343fa366-4fe4-11e8-8de8-4042a6b03170.png)

**Comment by andrewsyc** [comment]
@AlexM71  there's nothing I can do, I did get the original source code for tombviewer but I can't get this to work or troubleshoot on your computer. 
You'll need to try running compatibility mode, that's your best bet.
